language: java
deploy:
  provider: heroku
  api_key:
    secure: "bKHCE5OSw59KszVhMQc/bFJGyNVjmndzbHsFev55ySRY3T4o42cDAkEC3rb8Cb/CRDdcqjhgpsA5WqDl3vEqxbHY7817o4v29wrHUGd6DSOx7AKR5kdkppiN4ecvzKqHKtAh47EainwVorbVm2pLMf35r7svy0R7m3dFQcKSYXk="
  app: targetshootingdatabase
