language: java
deploy:
  provider: heroku
  api_key:
    secure: "jm+AYm4Enq6cdb5zKkf4a1e3MKlIdqSdesDIoVxytnzrLwKkP3P01k/FEsWAfIwiycrhI/oWy9A0sse8tra90JqaCEtXVFfFGUXcG7yrKGuCCG5CSLeaWNsyo5FKMqW49VfOMyS8m4GoK2/6DvC+G+q7QlZUfuCsIOlghUTGgwU="
  app: targetshootingdatabase
