swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /shooter/{id}:
    x-swagger-router-controller: shooter
    get:
      description: Returns the shooter with the specified ID
      operationId: getShooterById
      parameters:
        - name: id
          in: path
          description: The ID of the shooter
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
# complex objects have schema definitions
definitions:
  Shooter:
    required:
      - firstname
      - lastname
    properties:
      firstname:
        type: string
      lastname:
        type: string
  Error:
    required:
      - message
    properties:
      message:
        type: string
