swagger: "2.0"
info:
  version: "0.0.1"
  title: Target Shooting Database
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - application/octet-stream
produces:
  - application/json
paths:
  /shooter:
    x-swagger-router-controller: shooter
    get:
      description: Returns all shooters of the system
      operationId: getShooters
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: postShooterByName
      summary: Adds a shooter
      description: Adds one shooter by his first and lastname.
      parameters:
        - name: firstname
          in: query
          type: string
          description: Firstname of the shooter
          required: true
        - name: lastname
          in: query
          description: Lastname of the shooter
          type: string
          required: true
      responses:
        200:
          description: The saved shooter
          schema:
            $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /shooter/{id}:
    x-swagger-router-controller: shooter
    get:
      description: Returns the shooter with the specified ID
      operationId: getShooterById
      parameters:
        - name: id
          in: path
          description: The ID of the shooter
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event:
    x-swagger-router-controller: event
    get:
      operationId: getEvents
      summary: Returns all events of the system
      description: |
        An event links shooters and their results together.
        For example, an event may be a World Championship where many shooters
        shoot many results (each of them shooting one result).
        An event may also be a personal training where one shooter
        scores exactly one result.
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  Shooter:
    required:
      - firstname
      - lastname
    properties:
      firstname:
        type: string
      lastname:
        type: string
  Result:
    required:
      - score
      - category
      - time
    properties:
      score:
        type: number
        format: float
      category:
        type: string
      time:
        type: string
        format: date-time
      children:
        type: array
        items:
          $ref: '#/definitions/Result'
  Event:
    required:
      - description
    properties:
      description:
        type: string
      participations:
        type: array
        items:
          $ref: '#/definitions/Participation'
  Participation:
    required:
      - shooter
      - result
    properties:
      shooter:
        type: string
      result:
        type: string
  Error:
    required:
      - message
    properties:
      message:
        type: string
