swagger: "2.0"
info:
  version: "0.0.1"
  title: Target Shooting Database
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /shooters:
    x-swagger-router-controller: shooter
    get:
      description: Returns all shooters of the system
      operationId: getAllShooters
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /shooter/{id}:
    x-swagger-router-controller: shooter
    get:
      description: Returns the shooter with the specified ID
      operationId: getShooterById
      parameters:
        - name: id
          in: path
          description: The ID of the shooter
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Shooter"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  Shooter:
    required:
      - firstname
      - lastname
    properties:
      firstname:
        type: string
      lastname:
        type: string
  Error:
    required:
      - message
    properties:
      message:
        type: string
